version: '3.7'

services:
  web:
    container_name: nginx-server
    image: nginx:1.21.4-alpine
    restart: always
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - postgres
  php:
    container_name: php-server
    ports:
      - "9001:9000"
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
  postgres:
    image: postgres:14.0-alpine
    container_name: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:


